"""initial schema

Revision ID: ab559c318c98
Revises: 
Create Date: 2026-03-17 10:06:09.249916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab559c318c98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rulesets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=50), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('rule_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ruleset_id', sa.String(length=36), nullable=False),
    sa.Column('original_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('source_addresses', sa.Text(), nullable=True),
    sa.Column('source_ports', sa.Text(), nullable=True),
    sa.Column('dest_addresses', sa.Text(), nullable=True),
    sa.Column('dest_ports', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('collection_priority', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ruleset_id'], ['rulesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('related_rule_ids', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_reports.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.String(length=50), nullable=False),
    sa.Column('control_id', sa.String(length=20), nullable=False),
    sa.Column('control_title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('affected_rule_ids', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compliance_checks')
    op.drop_table('chat_messages')
    op.drop_table('audit_findings')
    op.drop_table('rules')
    op.drop_table('audit_reports')
    op.drop_table('rulesets')
    # ### end Alembic commands ###
